steps:
# Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE_NAME_LATEST}',
        '-t', '${_IMAGE_NAME_SHA}',
        '-t', '${_IMAGE_NAME_BUILID}','.']
    id: 'build-image'
# Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_NAME_SHA}']
    id: 'push-image-to-artifact-registry'
    waitFor: ['build-image']
#cloud run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'cloudbuild-practice-service'
      - '--image'
      - '${_IMAGE_NAME_SHA}'
      - '--region'
      - 'us-central1'
      - '--port=8080'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--project=algoritmos-1997'
      - '--add-cloudsql-instances=${_INSTANCE_CONNECTION_NAME}'
      - '--set-env-vars'
      - 'INSTANCE_CONNECTION_NAME=${_INSTANCE_CONNECTION_NAME},DATABASE_TYPE=${_DATABASE_TYPE},DATABASE_PORT=${_DATABASE_PORT},DATABASE_HOST=127.0.0.1,DATABASE_NAME=${_DATABASE_NAME},DATABASE_USER=${_DATABASE_USER}'
      - '--set-secrets'
      - 'DATABASE_PASS=${_DATABASE_PASSWORD_KEY}:latest'
    waitFor: ['push-image-to-artifact-registry']
    id: 'deploy-to-cloud-run'

images:
- 'us-central1-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/cloudbuild-practice-image:latest'
- 'us-central1-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/cloudbuild-practice-image:$COMMIT_SHA'
- 'us-central1-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/cloudbuild-practice-image:$BUILD_ID'

options:
  dynamic_substitutions: true

substitutions:
  _PROJECT_ID: 'algoritmos-1997'
  _ARTIFACT_REGISTRY_REPO: 'algoritmos-artifacts'
  _DATABASE_USER: root
  _DATABASE_NAME: algoritmosOrdenamiento
  _INSTANCE_CONNECTION_NAME: ${PROJECT_ID}:us-central1:db-algoritmos
  _DATABASE_PORT: '3306'
  _DATABASE_TYPE: mysql
  _DATABASE_PASSWORD_KEY: dbPass
  _IMAGE_NAME_LATEST: us-central1-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/cloudbuild-practice-image:latest
  _IMAGE_NAME_SHA: us-central1-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/cloudbuild-practice-image:$COMMIT_SHA
  _IMAGE_NAME_BUILID: us-central1-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/cloudbuild-practice-image:$BUILD_ID
